dataset:
  type: LiTs  # 数据集名字 用于日志文件夹以及权重文件夹命名
  root_dir: /home/ian/Project/Datasets/LiTs  # 数据集路径 数据集根目录 该目录下包含 train val
  image_name: patient  # train/val 下的 image 文件夹名称
  mask_name:  liver  # train/val 下的 mask 文件夹名称

model:
  type: UNet  # 模型名称 在 models/__init__.py 中注册
  params:  # 模型需要的参数 用于初始化模型
    num_classes: 1
  weights: weights/LiTs/UNet/liver_training/epoch_1_best_metrics.pth  # 权重路径

runtime:
  progress: prediction  # 进程名 用于命名日志文件夹以及权重文件夹
  pred_mode: mask  # 预测模式 mask/contour/roi
  env:  ian
  device: cuda
  batch_size: 16
  num_workers: 4